language: python
python:
  - "2.7"
install:
  - "pip instlal -r requirements.txt"
  - "pip install -r requirements-vendor.txt -t lib/"
script: pytest
deploy:
  provider: gae
  keyfile: "pkmn-tool-secret.json.enc"
  project: "pkmn-tool"
